language: java

jdk: oraclejdk11

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- chmod 600 ~/.netrc

install:
- git clone https://github.com/ctlab/private-libraries.git lib
- mvn install:install-file -Dfile=lib/lib/cplex.jar -DgroupId=com.ibm -DartifactId=cplex -Dversion=12.7.1 -Dpackaging=jar

script:
- mvn install -DskipTests=true
- java -Djava.library.path=lib/lib -cp lib/lib/cplex.jar:target/gmwcs-solver.jar ru.ifmo.ctddev.gmwcs.Main -n nodes -e edges
- mvn -Djava.library.path=lib/lib test

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  file: target/gmwcs-solver.jar
  skip_cleanup: true
  on:
    tags: true
